# ny: 120
# nx: 130
# nt: 1000
# dx: 4.0
# dy: 4.0
# dt: 0.0001

pml_width: 20
vel: 1500.0

n_shots: 1

freq: 25.0
peak_time_factor: 1.5

n_epochs: 100
lr: 0.1

editor: null
device: 'cuda:0'

ref_loc: [0.5, 0.5]
init_loc: [0.6, 0.5]

beta: [4.0, 4.0]
halfwidth: [70, 70]

dupe: False

delta: 25
step: 10
