#
# @VS@ cd _dir/../.. && python main.py

defaults:
- hydra: default
- _self_

device: "cuda:0"
nt: 1000
dt: 0.004
grid_spacing: [10.0, 10.0]
nx: 50
ny: 50
vp: 1500.0
src_loc: [[[25, 25]]]
rec_locs:
  method: cartesian
  fixed_y: 2
  x_stride: 5

ground_truth:
  mu: [25.0, 25.0]
  sig: [0.1, 0.1]
  peak_time: 0.2
  freq: 25.0
  scale: 1.0

init:
  mu: 
    val: [25.0, 25.0]
    train: true
  sig: 
    val: [5.0, 5.0]
    train: false
  peak_time: 
    val: 0.2
    train: true
  freq: 
    val: 23.0
    train: true
  scale: 
    val: ${ground_truth.scale}
    train: false

optim:
  name: Adam
  params:
    lr: 0.05

loss:
  abs_loss_tol: 1e-9

alphas: [1.0]
gamma: 0.2

training:
  num_epochs: 10000
  history_freq: 25
snr: 100.0
dupe: 
  - out.txt
  - ${oc.env:PWD}/latest_run.txt
