---
seq:
  - float32
  - [1.0, 3]
  - [2, 3]
  - [1, 2]
  - [1, 3]
  - [2, 3]
  - [1, 2]
  - [1, 3]
  - [2, 3]

beat_unit: 8
num_units: 4
bpm: 128
fps: 24
subdivs: 4
start_beat: 0
default_type: int

anim:
  rotate:
    - [0, 0, 0]
    - [45, 0, 0]
    - [90, 0, 0]
    - [135, 0, 0]
    - [180, 0, 0]
    - [225, 0, 0]
    - [270, 0, 0]
    - [315, 0, 0]
