---
seq:
  - float32
  - [1, 3]
  - [2, 3]
  - [1, 2]
  - [1, 3]
  - [2, 3]
  - [1, 2]
  - [1, 3]
  - [2, 3]

beat_unit: 8
num_units: 4
bpm: 128
fps: 24
subdivs: 4
start_beat: 0
default_type: int

# anim:
#   rotate:
#     - [0, 0, 0]
#     - [45, 0, 0]
#     - [45, 45, 0]
#     - [45, 45, 45]
#     - [45, 45, 0]
#     - [45, 0, 0]

anim:
  scale:
    ref: [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]
    pop: [[2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5]]
