#
# @VS@ cd _dir/../.. && python a.py 
defaults:
  - hydra: hydra_defaults
  - _self_
  - disc: default
  - medium: default
  - resolve_order: default
  - rec_loc: default
  - src: default
  - forward: default
  - obs: default
  - train: default

# Device settings
device: cuda:0         # Use GPU if available
