first:
  begin:
    month: July
    day: 1
    year: 1942

  end:
    month: July
    day: 27
    year: 1942

  victor: stalemate

second:
  begin:
    month: October
    day: 23
    year: 1942

  end:
    month: November
    day: 4
    year: 1942

  victor: allies
